Mise à jour du texte du tweet.
MattiSG/comment-voter pull request #3
Opened 2016-12-04 18:05 UTC by ColinMaudry

Mise à jour du texte du tweet de partager pour coller au contexte de fin d'année 2016.

2016-12-05 21:06 UTC, MattiSG requested changes
Oui, c'est bien dépassé ! Merci pour la vigilance !

2016-12-05 21:06 UTC, MattiSG commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et ainsi pouvoir voter en 2017. → http://comment-voter.fr">
L'URL est ajoutée automatiquement, pas besoin de l'indiquer ici.

2016-12-05 21:06 UTC, MattiSG commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et ainsi pouvoir voter en 2017. → http://comment-voter.fr">
Neutralité de genre : `inscrit·e`

2016-12-05 21:06 UTC, MattiSG commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et ainsi pouvoir voter en 2017. → http://comment-voter.fr">
Un hashtag serait bienvenu pour augmenter la découvrabilité du tweet.

2016-12-05 21:24 UTC, ColinMaudry commented
https://twitter.com/hashtag/elections2017 ?

2016-12-05 21:59 UTC, MattiSG commented
Soit ça soit #presidentielle2017. Je ne sais pas lequel est le plus populaire. Ou peut-être a-t-on la place de mettre les deux ??

2016-12-06 19:05 UTC, MattiSG requested changes
Merci pour les modifications ! Si ces allers-retours t'agacent, n'hésite pas à me demander de prendre en charge la finalisation de la PR  :)

2016-12-06 19:05 UTC, MattiSG commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit·e sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et pouvoir voter #Elections2017">
Pour que le hashtag soit ajouté et non considéré comme une ancre, il faut soir [encoder l'URL](http://urlencode.org) soit utiliser le [paramètre `hashtag`](https://dev.twitter.com/web/tweet-button/web-intent).

En fait, le mieux serait probablement de faire les deux :wink:

2016-12-06 19:09 UTC, ColinMaudry commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit·e sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et pouvoir voter #Elections2017">
Tu as besoin que je fasse quelque chose pour que tu puisses finaliser la PR ? Mais effectivement à ce niveau c'est certainement plus simple.

2016-12-06 19:13 UTC, MattiSG commented on index.html
> +				href="https://twitter.com/intent/tweet?text=Es-tu inscrit·e sur les listes électorales ? Tu as jusqu'au 31/12 pour le faire et pouvoir voter #Elections2017">
Oui, il faut modifier l'URL car le hashtag n'est pas transmis dans la forme actuelle (il est interprété comme une ancre par le navigateur).

Je prends la modif :)

2016-12-06 19:17 UTC, MattiSG approved these changes

2016-12-06 19:17 UTC, merged

2016-12-06 19:18 UTC, MattiSG commented
Merci Colin !!